### ISSUE TITLE
ember install ember-perfectscroll not working

### ISSUE THREAD

**Issue by thilinadinith** [imanhodjaev/ember-perfect-scroll#27]
this is not working giving an npm error as follow 
```
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/Users/Thilina/Documents/work/github.com/study-web/node_modules/npm/node_modules/cmd-shim/node_modules/gra
ceful-fs/fs.js:11:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

    at tryModuleLoad (module.js:505:12)
error: --------------------------------------------------------------------------
```

**Comment by cannyedge34** [comment]
Same
